networks:
  deploy-dev:
    driver: bridge
services:
  identity:
    container_name: identity-service
    image: identity
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
    ports:
      - "8080:8080"
    networks:
      - deploy-dev
    depends_on:
      - identity-db
  identity-db:
    container_name: identity-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: identity_db
      PGPORT: 5433
    ports:
      - "5433:5433"
    networks:
      - deploy-dev
    volumes:
      - .postgres-data:/data
volumes:
  postgres-data:
